name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Cypress Run
        run: npm run cypress:run
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Mochawesome Report
        run: |
          mkdir -p public/mochawesome-report
          if [ -d "cypress/reports/mochawesome" ]; then
            cp -r cypress/reports/mochawesome/* public/mochawesome-report || echo "No report files to copy"
          else
            echo "Mochawesome report directory does not exist"
          fi
        
      - name: Deploy Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GH_TOKEN }}
            publish_dir: ./public