name: Cypress Tests

on:
  push:
    branches:
      - main 

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Tests
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        run: |
          npm run cypress:run --record --parallel --group "github-action-parallel-1" --ci-build-id ${{ github.run_id }}
