name: Cypress Tests

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome106-ff106

    strategy:
      fail-fast: false
      matrix:
        container: [1, 2]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install # ติดตั้ง dependencies ทั้งหมดจาก package.json

      - name: Install Cypress Binary
        run: npx cypress install # ติดตั้ง Cypress Binary เพิ่มเติมเพื่อให้พร้อมใช้งาน

      - name: Prepare Cypress Folders
        run: |
          mkdir -p cypress/videos cypress/screenshots
          chmod -R 777 ./cypress

      - name: Run Cypress Tests in Parallel
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run cypress:run --record --parallel --group "github-action-parallel-${{ matrix.container }}" --ci-build-id ${{ github.run_id }} --reporter mochawesome --reporter-options "reportDir=cypress/reports,overwrite=true,html=true,json=true"

      - name: Merge Reports
        run: |
          npx mochawesome-merge cypress/reports/*.json > cypress/reports/combined-report.json

      - name: Generate Report
        run: |
          if [ -f cypress/reports/combined-report.json ]; then
            npx marge cypress/reports/combined-report.json -f report -o cypress/reports
          else
            echo "Report file not found. Skipping report generation."
          fi
