name: Cypress Tests

# กำหนดให้ workflow นี้รันเมื่อมีการ push โค้ดไปที่ branch main
on:
    push:
      branches:
        - main 

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    # ตั้งค่าให้การทดสอบรันแบบขนาน โดยใช้กลยุทธ์ matrix
    # ใช้ 2 instances ทำให้การรันเร็วขึ้น
    strategy:
      fail-fast: false # กำหนดให้ไม่หยุดเมื่อเกิดข้อผิดพลาด (เพื่อรันงานอื่นให้ครบ)
      matrix:
        container: [1, 2] # ใช้ 2 instance รันพร้อมกัน

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # ดึงโค้ดจาก repository มายัง environment

      - name: Install Dependencies
        run: npm ci # ติดตั้ง dependencies อย่างครบถ้วน

      - name: Set Execute Permissions for Cypress
        run: chmod +x ./node_modules/.bin/cypress # กำหนดสิทธิ์ให้ Cypress เพื่อให้สามารถรันได้

      - name: Run Cypress Tests in Parallel
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }} # ใช้สำหรับบันทึกผลใน Cypress Cloud
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # ใช้สำหรับเชื่อมต่อกับ GitHub
        run: |
          npm run cypress:run --record --parallel --group "github-action-parallel-${{ matrix.container }}" --ci-build-id ${{ github.run_id }} --reporter mochawesome --reporter-options "reportDir=cypress/reports,overwrite=true,html=true,json=true"

  generate-report:
    needs: cypress-run # รันงานนี้หลังจาก cypress-run สำเร็จ
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Cypress JSON Reports
        uses: actions/download-artifact@v4  # อัปเดตเป็น v4 เพื่อรองรับ Node.js 20
        with:
          name: cypress-json-reports
          path: cypress/results

      - name: Install Dependencies
        run: npm ci

      - name: Merge JSON Reports
        run: |
          if ls cypress/reports/*.json 1> /dev/null 2>&1; then
            npx mochawesome-merge cypress/reports/*.json > cypress/reports/mochawesome.json
          else
            echo "No JSON reports found to merge."
            exit 1
          fi

      - name: Generate HTML Report
        run: |
          if [ -f cypress/reports/mochawesome.json ]; then
            npx mochawesome-report-generator cypress/reports/mochawesome.json -o cypress/reports/html
          else
            echo "Merged JSON report not found."
            exit 1
          fi

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-mochawesome-rep