name: Cypress Tests

on:
  push:
    branches:
      - 'main'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome106-ff106

    strategy:
      fail-fast: false
      matrix:
        container: [1, 2]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install # ติดตั้ง dependencies ทั้งหมดจาก package.json

      - name: Run Cypress Tests in Parallel
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run cypress:run --record --parallel --group "github-action-parallel-${{ matrix.container }}" --ci-build-id ${{ github.run_id }} --reporter mochawesome --reporter-options "reportDir=cypress/reports,overwrite=true,html=true,json=true"

