name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (specify your Node version if needed)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Clear Cypress cache (if needed)
      - name: Clear Cypress cache
        run: rm -rf ~/.cache/Cypress

      # Step 5: Run Cypress tests
      - name: Run Cypress in parallel with mochawesome reporter
        env:
          # Add Cypress record key here
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        run: |
          npm run cypress:run --record --parallel --group "github-action-parallel-1" --ci-build-id 11605682783 --reporter mochawesome --reporter-options "reportDir=cypress/reports,overwrite=true,html=true,json=true"
