name: Cypress Tests

# กำหนดให้ workflow นี้รันเมื่อมีการ push โค้ดไปที่ branch main
on:
    push:
      branches:
        - main 

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.18.0-chrome83-ff77
      
    # ตั้งค่าให้การทดสอบรันแบบขนาน โดยใช้กลยุทธ์ matrix
    # ใช้ 2 instances ทำให้การรันเร็วขึ้น
    strategy:
      fail-fast: false # กำหนดให้ไม่หยุดเมื่อเกิดข้อผิดพลาด (เพื่อรันงานอื่นให้ครบ)
      matrix:
        container: [1, 2] # ใช้ 2 instance รันพร้อมกัน

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # ดึงโค้ดจาก repository มายัง environment

      - name: Install Dependencies
        run: npm ci # ติดตั้ง dependencies อย่างครบถ้วน

      - name: Set Execute Permissions for Cypress
        run: chmod +x ./node_modules/.bin/cypress # กำหนดสิทธิ์ให้ Cypress เพื่อให้สามารถรันได้

      - name: Run Cypress Tests in Parallel
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }} # ใช้สำหรับบันทึกผลใน Cypress Cloud
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # ใช้สำหรับเชื่อมต่อกับ GitHub
        run: |
          npm run cypress:run --record --parallel --group "github-action-parallel-${{ matrix.container }}" --ci-build-id ${{ github.run_id }} --reporter mochawesome --reporter-options "reportDir=cypress/reports,overwrite=true,html=true,json=true"
          continue-on-error: true
          
      - name: Copy test execution videos and screenshots
        run: |
          mkdir public
          cp -r cypress/videos public/videos
          cp -r cypress/screenshots public/screenshots

      - name: Merge test reports
        run: npm run combine:report

      - name: Generate HTML report
        run: npm run generate:report
      
      - name: Deploy report page to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
