name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Cypress Run
        run: npm run cypress:run
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Mochawesome Report
      #   run: |
      #     mkdir -p public/mochawesome-report
      #     if [ -d "cypress/reports/mochawesome" ]; then
      #       cp -r cypress/reports/mochawesome/* public/cypress/reports || echo "No report files to copy"
      #     else
      #       echo "Mochawesome report directory does not exist"
      #     fi

      - name: Merge Mochawesome Reports
        run: |
          npx mochawesome-merge cypress/reports/mochawesome/*.json > mochawesome.json || echo "No report found"
          npx marge mochawesome.json --reportDir ./public/cypress/reports --inline || echo "No merged report found"
      
      - name: Copy Videos and Screenshots
        run: |
          mkdir -p public/cypress/videos public/cypress/screenshots
          cp -r cypress/videos/* public/cypress/videos || echo "No videos to copy"
          cp -r cypress/screenshots/* public/cypress/screenshots || echo "No screenshots to copy"
  
      - name: Deploy Report Page to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
            github_token: ${{ secrets.GH_TOKEN }}
            publish_dir: ./public

      - name: Auto Merge Pull Request
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          gh pr merge $PR_NUMBER --merge --admin